# Greenhouse Slug Discovery

This notebook tests candidate Greenhouse board slugs against:

`https://boards-api.greenhouse.io/v1/boards/{slug}/jobs`

A slug is considered **working** when the API responds `200 OK`.

## Is this possible?

Yes. Greenhouse board URLs are public and can be probed by slug.

- `200` means the board exists and is reachable.
- `404` usually means no board for that slug.

> Note: this cannot guarantee a complete list of *all* companies using Greenhouse.
> It only validates the candidate slugs you provide.

In [1]:
import time
import random
from concurrent.futures import ThreadPoolExecutor, as_completed
from typing import Iterable

import requests
import pandas as pd

In [2]:
# --- Configuration ---
BASE_URL = "https://boards-api.greenhouse.io/v1/boards/{slug}/jobs"
MAX_WORKERS = 12
REQUEST_TIMEOUT = 12
SLEEP_JITTER_SEC = (0.0, 0.15)  # polite jitter between calls in each worker

# Seed list from the app's current curated companies.
seed_slugs = [
    "airbnb", "amplitude", "anthropic", "asana", "benchling", "brex", "canva", "cloudflare",
    "coinbase", "datadog", "databricks", "discord", "doordash", "dropbox", "duolingo",
    "figma", "fivetran", "gitlab", "gusto", "hashicorp", "hubspot", "intercom", "lattice",
    "launchdarkly", "linear", "loom", "lyft", "mercury", "miro", "mixpanel", "mongodb",
    "notion", "pagerduty", "palantir", "pinterest", "plaid", "ramp", "reddit", "retool",
    "rippling", "robinhood", "scale", "segment", "snowflake", "stripe", "twilio", "verkada",
    "zendesk", "zoom"
]

# Add your own guesses here (lowercase slug format):
extra_candidates = pd.read_csv("/Users/giulioelmi/Desktop/job-finder/notebooks/companies.csv")["company"].dropna().tolist()

candidates = sorted(set(seed_slugs + extra_candidates))
print(f"Total candidate slugs: {len(candidates)}")

Total candidate slugs: 1047

In [3]:
def probe_slug(slug: str) -> dict:
    url = BASE_URL.format(slug=slug)
    t0 = time.perf_counter()
    try:
        r = requests.get(url, timeout=REQUEST_TIMEOUT)
        elapsed_ms = round((time.perf_counter() - t0) * 1000, 1)
        # jitter to be polite when running high concurrency
        time.sleep(random.uniform(*SLEEP_JITTER_SEC))

        return {
            "slug": slug,
            "status_code": r.status_code,
            "ok": r.status_code == 200,
            "jobs_count": len(r.json().get("jobs", [])) if r.status_code == 200 else None,
            "url": url,
            "elapsed_ms": elapsed_ms,
        }
    except Exception as e:
        elapsed_ms = round((time.perf_counter() - t0) * 1000, 1)
        return {
            "slug": slug,
            "status_code": None,
            "ok": False,
            "jobs_count": None,
            "url": url,
            "elapsed_ms": elapsed_ms,
            "error": str(e),
        }


def scan_slugs(slugs: Iterable[str]) -> pd.DataFrame:
    rows = []
    with ThreadPoolExecutor(max_workers=MAX_WORKERS) as pool:
        futures = {pool.submit(probe_slug, s): s for s in slugs}
        for fut in as_completed(futures):
            rows.append(fut.result())
    df = pd.DataFrame(rows).sort_values(["ok", "status_code", "slug"], ascending=[False, True, True])
    return df.reset_index(drop=True)

In [12]:
results = scan_slugs(candidates)
results.head(200)

,slug,status_code,ok,jobs_count,url,elapsed_ms
0,2U,200,True,29.0,https://boards-api.greenhouse.io/v1/boards/2U/...,273.7
1,6sense,200,True,29.0,https://boards-api.greenhouse.io/v1/boards/6se...,202.0
2,ASG,200,True,2.0,https://boards-api.greenhouse.io/v1/boards/ASG...,218.5
3,Acquia,200,True,10.0,https://boards-api.greenhouse.io/v1/boards/Acq...,125.5
4,Affirm,200,True,163.0,https://boards-api.greenhouse.io/v1/boards/Aff...,131.4
...,...,...,...,...,...,...
195,Amazon Pay,404,False,NaN,https://boards-api.greenhouse.io/v1/boards/Ama...,150.8
196,Amazon Web Services,404,False,NaN,https://boards-api.greenhouse.io/v1/boards/Ama...,139.9
197,Amdocs,404,False,NaN,https://boards-api.greenhouse.io/v1/boards/Amd...,138.0
198,Amelia,404,False,NaN,https://boards-api.greenhouse.io/v1/boards/Ame...,140.0
199,Ameren,404,False,NaN,https://boards-api.greenhouse.io/v1/boards/Ame...,262.9

In [15]:
results["url"].tail(200)

847     https://boards-api.greenhouse.io/v1/boards/Spl...
848     https://boards-api.greenhouse.io/v1/boards/Spo...
849     https://boards-api.greenhouse.io/v1/boards/Spr...
850     https://boards-api.greenhouse.io/v1/boards/Spr...
851     https://boards-api.greenhouse.io/v1/boards/Spr...
                              ...
1042    https://boards-api.greenhouse.io/v1/boards/sno...
1043    https://boards-api.greenhouse.io/v1/boards/sym...
1044    https://boards-api.greenhouse.io/v1/boards/tes...
1045    https://boards-api.greenhouse.io/v1/boards/zen...
1046    https://boards-api.greenhouse.io/v1/boards/zoo...
Name: url, Length: 200, dtype: object

In [5]:
summary = (
    results.assign(status_group=results["status_code"].fillna(-1))
    .groupby("status_group", dropna=False)
    .size()
    .rename("count")
    .reset_index()
    .sort_values("status_group")
)
summary

   status_group  count
0           200    154
1           404    893

In [ ]:
working = results[results["ok"]].copy()
print(f"Working slugs: {len(working)}")
working[["slug", "jobs_count", "status_code", "elapsed_ms"]].head
(50)

Working slugs: 154

             slug  jobs_count  status_code  elapsed_ms
104         Toast       275.0          200       152.1
105   Transcarent        31.0          200       163.8
106   Tripadvisor        63.0          200       137.8
107        Turing        28.0          200       177.0
108        Twilio       127.0          200       173.0
109       Upgrade        18.0          200       132.3
110       Upstart        70.0          200       141.3
111        Vonage        80.0          200       144.4
112         Waymo       419.0          200       147.2
113         Wrike        49.0          200       141.0
114       Xometry       421.0          200      1075.2
115          Yext         6.0          200       188.1
116        Zinnia        59.0          200       143.6
117  ZipRecruiter        43.0          200       142.2
118      ZoomInfo        72.0          200       161.3
119       Zscaler       297.0          200       134.0
120         Zuora        55.0          200       136.2
121        airbnb       257.0          200       148.1
122     amplitude        59.0          200       147.0
123     anthropic       450.0          200       161.1
124         asana       166.0          200       128.6
125          brex       246.0          200       142.4
126    cloudflare       577.0          200       142.3
127      coinbase       225.0          200       145.6
128    databricks       763.0          200       184.6
129       datadog       440.0          200       174.0
130       discord        81.0          200       143.4
131       dropbox       138.0          200       136.7
132      duolingo        84.0          200       121.3
133         figma       172.0          200       169.4
134      fivetran       170.0          200       174.4
135        gitlab       163.0          200       185.5
136         gusto        75.0          200       163.2
137       hubspot         0.0          200       142.2
138          iFit        25.0          200       186.9
139      intercom       218.0          200       190.2
140       lattice        17.0          200       197.2
141  launchdarkly        58.0          200       225.1
142          lyft       163.0          200       246.8
143       mercury        54.0          200       172.7
144      mixpanel        40.0          200       194.2
145       mongodb       409.0          200       175.7
146     pagerduty        45.0          200       141.5
147     pinterest       107.0          200       206.7
148        reddit       143.0          200       177.3
149     robinhood       142.0          200       230.4
150        stripe       560.0          200       178.6
151        twilio       127.0          200       143.6
152       verkada       313.0          200       139.9
153           xAI       191.0          200       133.3

In [7]:
# Save results for later use.
output_csv = "greenhouse_slug_scan_results.csv"
results.sort_values(["ok", "slug"], ascending=[False, True]).to_csv(output_csv, index=False)
print(f"Saved: {output_csv}")

Saved: greenhouse_slug_scan_results.csv

---

## Ashby API Check

Testing the same candidate slugs against the Ashby public job board API:

`https://api.ashbyhq.com/posting-api/job-board/{slug}`

- `200` means the company has an Ashby job board at that slug.
- `404` / other means no board found.

> Slugs are case-sensitive in Ashby — this first pass uses lowercase (same as Greenhouse slugs).

In [9]:
ASHBY_BASE_URL = "https://api.ashbyhq.com/posting-api/job-board/{slug}"

def probe_ashby_slug(slug: str) -> dict:
    url = ASHBY_BASE_URL.format(slug=slug)
    t0 = time.perf_counter()
    try:
        r = requests.get(url, timeout=REQUEST_TIMEOUT)
        elapsed_ms = round((time.perf_counter() - t0) * 1000, 1)
        time.sleep(random.uniform(*SLEEP_JITTER_SEC))

        jobs = []
        if r.status_code == 200:
            data = r.json()
            jobs = data.get("jobs", [])

        return {
            "slug": slug,
            "status_code": r.status_code,
            "ok": r.status_code == 200,
            "jobs_count": len(jobs) if r.status_code == 200 else None,
            "url": url,
            "elapsed_ms": elapsed_ms,
        }
    except Exception as e:
        elapsed_ms = round((time.perf_counter() - t0) * 1000, 1)
        return {
            "slug": slug,
            "status_code": None,
            "ok": False,
            "jobs_count": None,
            "url": url,
            "elapsed_ms": elapsed_ms,
            "error": str(e),
        }


def scan_ashby_slugs(slugs) -> pd.DataFrame:
    rows = []
    with ThreadPoolExecutor(max_workers=MAX_WORKERS) as pool:
        futures = {pool.submit(probe_ashby_slug, s): s for s in slugs}
        for fut in as_completed(futures):
            rows.append(fut.result())
    df = pd.DataFrame(rows).sort_values(["ok", "status_code", "slug"], ascending=[False, True, True])
    return df.reset_index(drop=True)

In [10]:
ashby_results = scan_ashby_slugs(candidates)

ashby_working = ashby_results[ashby_results["ok"]].copy()
print(f"Working Ashby slugs: {len(ashby_working)} / {len(candidates)}")
ashby_results

Working Ashby slugs: 40 / 1047

,slug,status_code,ok,jobs_count,url,elapsed_ms
0,Applied Intuition,200,True,0.0,https://api.ashbyhq.com/posting-api/job-board/...,279.9
1,Boomi,200,True,0.0,https://api.ashbyhq.com/posting-api/job-board/...,277.2
2,Centerfield,200,True,20.0,https://api.ashbyhq.com/posting-api/job-board/...,590.9
3,Confluent,200,True,58.0,https://api.ashbyhq.com/posting-api/job-board/...,666.4
4,Crusoe,200,True,306.0,https://api.ashbyhq.com/posting-api/job-board/...,4737.4
...,...,...,...,...,...,...
1042,test IO,404,False,NaN,https://api.ashbyhq.com/posting-api/job-board/...,324.7
1043,twilio,404,False,NaN,https://api.ashbyhq.com/posting-api/job-board/...,269.7
1044,xAI,404,False,NaN,https://api.ashbyhq.com/posting-api/job-board/xAI,313.1
1045,zendesk,404,False,NaN,https://api.ashbyhq.com/posting-api/job-board/...,465.0
1046,zoom,404,False,NaN,https://api.ashbyhq.com/posting-api/job-board/...,326.7

In [21]:
ashby_working.head(50)

,slug,status_code,ok,jobs_count,url,elapsed_ms
0,Applied Intuition,200,True,0.0,https://api.ashbyhq.com/posting-api/job-board/...,279.9
1,Boomi,200,True,0.0,https://api.ashbyhq.com/posting-api/job-board/...,277.2
2,Centerfield,200,True,20.0,https://api.ashbyhq.com/posting-api/job-board/...,590.9
3,Confluent,200,True,58.0,https://api.ashbyhq.com/posting-api/job-board/...,666.4
4,Crusoe,200,True,306.0,https://api.ashbyhq.com/posting-api/job-board/...,4737.4
5,Dandy,200,True,143.0,https://api.ashbyhq.com/posting-api/job-board/...,2086.1
6,Delinea,200,True,105.0,https://api.ashbyhq.com/posting-api/job-board/...,1546.8
7,Everbridge,200,True,0.0,https://api.ashbyhq.com/posting-api/job-board/...,332.2
8,Handshake,200,True,89.0,https://api.ashbyhq.com/posting-api/job-board/...,1634.3
9,Harmonic,200,True,7.0,https://api.ashbyhq.com/posting-api/job-board/...,339.9
10,KAYAK,200,True,37.0,https://api.ashbyhq.com/posting-api/job-board/...,250.9
11,Lemonade,200,True,61.0,https://api.ashbyhq.com/posting-api/job-board/...,198.3
12,Machinify,200,True,1.0,https://api.ashbyhq.com/posting-api/job-board/...,260.9
13,Mercury,200,True,0.0,https://api.ashbyhq.com/posting-api/job-board/...,228.9
14,Olive,200,True,2.0,https://api.ashbyhq.com/posting-api/job-board/...,245.0
15,OpenAI,200,True,615.0,https://api.ashbyhq.com/posting-api/job-board/...,8100.1
16,Qualtrics,200,True,0.0,https://api.ashbyhq.com/posting-api/job-board/...,309.7
17,Rev,200,True,4.0,https://api.ashbyhq.com/posting-api/job-board/Rev,274.7
18,Saronic,200,True,243.0,https://api.ashbyhq.com/posting-api/job-board/...,5017.4
19,Snowflake,200,True,416.0,https://api.ashbyhq.com/posting-api/job-board/...,5059.6
20,Snyk,200,True,0.0,https://api.ashbyhq.com/posting-api/job-board/...,382.8
21,SpotOn,200,True,130.0,https://api.ashbyhq.com/posting-api/job-board/...,2015.3
22,Spreetail,200,True,0.0,https://api.ashbyhq.com/posting-api/job-board/...,354.0
23,Taekus,200,True,7.0,https://api.ashbyhq.com/posting-api/job-board/...,388.4
24,Talkdesk,200,True,0.0,https://api.ashbyhq.com/posting-api/job-board/...,259.5
25,Tekion,200,True,0.0,https://api.ashbyhq.com/posting-api/job-board/...,256.2
26,UiPath,200,True,127.0,https://api.ashbyhq.com/posting-api/job-board/...,2102.1
27,Vanta,200,True,186.0,https://api.ashbyhq.com/posting-api/job-board/...,2731.8
28,benchling,200,True,55.0,https://api.ashbyhq.com/posting-api/job-board/...,875.9
29,launchdarkly,200,True,0.0,https://api.ashbyhq.com/posting-api/job-board/...,181.6
30,linear,200,True,20.0,https://api.ashbyhq.com/posting-api/job-board/...,181.4
31,loom,200,True,0.0,https://api.ashbyhq.com/posting-api/job-board/...,175.8
32,mercury,200,True,0.0,https://api.ashbyhq.com/posting-api/job-board/...,190.2
33,notion,200,True,156.0,https://api.ashbyhq.com/posting-api/job-board/...,553.8
34,plaid,200,True,97.0,https://api.ashbyhq.com/posting-api/job-board/...,1882.9
35,ramp,200,True,132.0,https://api.ashbyhq.com/posting-api/job-board/...,303.3
36,reddit,200,True,0.0,https://api.ashbyhq.com/posting-api/job-board/...,286.1
37,retool,200,True,0.0,https://api.ashbyhq.com/posting-api/job-board/...,236.1
38,snowflake,200,True,416.0,https://api.ashbyhq.com/posting-api/job-board/...,391.7
39,verkada,200,True,0.0,https://api.ashbyhq.com/posting-api/job-board/...,372.9